// TODO: should be set by user config?!
export const testWrapperIdentifiers = [
  'it',
  'it.skip',
  'it.skipIf',
  'it.runIf',
  'it.only',
  'it.concurrent',
  'it.todo',
  'it.fails',
  'it.each',
  'test',
  'test.skip',
  'test.skipIf',
  'test.runIf',
  'test.only',
  'test.concurrent',
  'test.todo',
  'test.fails',
  'test.each',
  'describe',
  'describe.skip',
  'describe.only',
  'describe.concurrent',
  'describe.shuffle',
  'describe.todo',
  'describe.each',
];
